---
output: 
  html_document:
    code_folding: show
    theme: readable
    df_print: paged
editor_options:
    chink_output_type: console
---

<br>

<div style="text-align: center;">
<span class="h1">Logistic Regression for Multinomial and Ordinal responses</span>

<span class="h5">
Modern Social Analysis, HSE SPb<br>
*Course:* Quantitative Data Analysis
</span>

<span class="h4">
Vasily Khodakovsky</span>
</div>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

```


```{r include=FALSE}
#{r, results = "hide"}

Sys.setlocale("LC_ALL", "English")
```

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>

# Data

```{r}
library(foreign)
```

<br>

```{r}
data = read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")
```

<br>

```{r}
options(width = 1000)
tail(data)
```

<br>
<br>
<br>
<br>
<br>

# Multinomial regression

<br>

```{r}
library(sjPlot)
library(nnet)
m1 = multinom(prog ~ ses + math, data = data)
```

<br>

```{r}
summary(m1, Wald = T)
```

<br>
<br>
<br>

```{r}
exp(coef(m1))
```

<br>
<br>
<br>

```{r}
library(stargazer)
stargazer(m1, type = "text")
```

<br>
<br>
<br>

```{r}
library(pscl)
pR2(m1)
```

<br>

Bearable

<br>
<br>
<br>

```{r}
hitmiss(m1)
```

<br>
<br>
<br>

```{r}
plot_model(m1, type = "pred", terms = "math")
```

<br>
<br>
<br>

### Changing reference category

```{r}
data$prog2 = relevel(data$prog, ref = "academic")
m2 = multinom(prog2 ~ ses + math, data = data)
```

<br>

```{r}
summary(m2, Wald = T)
```

<br>
<br>
<br>

```{r}
stargazer(m2, type = "text")
```

<br>
<br>
<br>

### Dummy coding

```{r}
library(car)
data$voc = recode(data$prog, ' "vocation" = 1; else = 0 ')
table(data$prog)
```

<br>

```{r}
table(data$voc)
```

<br>

```{r}
data$gen = recode(data$prog, ' "general" = 1; else = 0 ')
table(data$prog)
```

<br>

```{r}
table(data$gen)
```

<br>

```{r}
data$ac = recode(data$prog, ' "academic" = 1; else = 0 ')
table(data$prog)
```

<br>

```{r}
table(data$ac)
```

<br>
<br>
<br>

### Binary regressions

```{r}
m_voc = glm(voc ~ ses + math, data = data, family = 'binomial')
m_gen = glm(gen ~ ses + math, data = data, family = 'binomial')
m_ac = glm(ac ~ ses + math, data = data, family = 'binomial')
```

<br>
<br>
<br>

```{r}
stargazer(m_voc, m_gen, m_ac, type = "text")
```

<br>

```{r}
exp(coef(m_voc))
```

<br>

```{r}
exp(coef(m_gen))
```

<br>

```{r}
exp(coef(m_ac))
```

<br>
<br>
<br>

```{r}
summary(m_voc)
```

<br>

```{r}
summary(m_gen)
```

<br>

```{r}
summary(m_ac)
```

<br>
<br>
<br>

```{r}
pR2(m_voc)
```

<br>

```{r}
pR2(m_gen)
```

<br>

```{r}
pR2(m_ac)
```

<br>
<br>
<br>

```{r}
hitmiss(m_voc)
```

<br>

```{r}
hitmiss(m_gen)
```

<br>

```{r}
hitmiss(m_ac)
```

<br>
<br>
<br>
<br>
<br>

# Ordered Regression

```{r}
library(carData)
data(WVS)
```

<br>
<br>
<br>

```{r}
library(MASS)
m3 = polr(poverty ~ religion + degree + age + gender + country, data = WVS)
tab_model(m3)
```

<br>
<br>
<br>

```{r}
plot_model(m3, type = "pred", terms = "age")
```

<br>
<br>
<br>

```{r}
pR2(m3)
```


<br>
<br>
<br>

```{r}
hitmiss(m3)
```

