---
output: 
  html_document:
    code_folding: show
    theme: readable
    df_print: paged
editor_options:
    chink_output_type: console
---

<br>

<div style="text-align: center;">
<span class="h1"><b>Quakers network</b></span>

<span class="h5">
<b>Modern Social Analysis, HSE SPb</b><br>
*Course:* <b>Social Network Analysis</b></span>

<span class="h4"><b>Vasily Khodakovsky</b></span>
</div>

<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# General information

```{r}
library(igraph)
node_q <- read.csv("C:/Users/Vasily/Downloads/quakers_nodelist.csv")
edge_q <- read.csv("C:/Users/Vasily/Downloads/quakers_edgelist.csv")
quakers <- graph_from_data_frame(d = edge_q, vertices = node_q, directed = TRUE)
```

<br>

```{r}
head(edge_q, 5)
```

<br>
<br>
<br>

```{r}
head(node_q, 5)
```

<br>
<br>
<br>
<br>
<br>

# Visualization

<br>

### Fruchteman-Reingold layout

```{r, fig.height = 10, fig.width = 10}
degree_q = degree(quakers, v = V(quakers), mode = "all") 

V(quakers)$color <- ifelse(V(quakers)$Gender=='male', "blue", "red")
```

<br>

```{r, fig.height = 10, fig.width = 10}
par(bg = "grey13", mar = c(0,0,0,0)) 
plot(quakers, layout = layout_with_fr(quakers),  
     vertex.label = V(quakers)$name,  
     edge.arrow.size = 0.3,
     edge.color = 'white',
     vertex.size = degree_q,
     vertex.label.cex = degree_q/11,
     vertex.label.color = 'white')
```

<br>
<br>
<br>

### Cluster Louvian layout

```{r}
quakersUn <- as.undirected(quakers)
cl_louv <- cluster_louvain(quakersUn)
```

<br>

#### Modularity:

```{r}
library(kableExtra)
modularity(cl_louv) %>% 
  setNames(c("Modulatity")) %>% 
  kbl() %>% 
  kable_classic(html_font = "Cambria")
```

<br>
<br>
<br>

#### Number of communities:

```{r}
com <- data.frame(sizes(cl_louv)) 
nrow(com) %>% 
  setNames(c("Number of communities")) %>% 
  kbl() %>% 
  kable_classic(html_font = "Cambria")
```

<br>
<br>
<br>

#### Betweenness centrality:

```{r}
betw <- betweenness(quakersUn)
betw[betw > 300] %>% sort(decreasing = TRUE) %>%
  as.data.frame %>%
  setNames(c("Betweenness centrality")) %>% 
  kbl() %>% 
  kable_classic(html_font = "Cambria")
```

<br>
<br>
<br>

#### Visualization:

```{r, fig.height = 10, fig.width = 10}
par(bg = "grey13", mar = c(0,0,0,0)) 
plot(cl_louv,
        quakersUn,
        col = membership(cl_louv),
        mark.groups = communities(cl_louv),
        edge.color = "white",
        vertex.label = V(quakersUn)$name,
        vertex.label.color = 'white',
        vertex.size = 3,
        vertex.label.cex = betweenness(quakersUn)/500)
```


